### ISSUE TITLE
Should zero Content-Length be printed too?

### ISSUE THREAD

**Issue by capezotte** [skarnet/tipidee#1]
I've written this short CGI script:

```
#!/bin/sh
echo Status: 307
echo Location: //youtu.be/dQw4w9WgXcQ
echo
```

On a web browser (Firefox 117.0 to be precise), it seems to hang forever and only redirects the user to the best song in the world if I `pkill tipideed`.

Running `curl -v 'http://localhost:8080/cgi-bin/rick'`:
```
*   Trying [::1]:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /cgi-bin/rick HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.3.0
> Accept: */*
> 
< HTTP/1.1 307 
< Date: Sun, 24 Sep 2023 05:53:41 GMT
< Accept-Ranges: none
< Cache-Control: private
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline';
< Referrer-Policy: no-referrer-when-downgrade
< Server: tipidee/0.0.1.0
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< Location: //youtu.be/dQw4w9WgXcQ
* no chunk, no close, no size. Assume close to signal end
< 
```

Also hangs forever, unless I `pkill tipidee`, after which curl says: `* Closing connection`.

I think I found a likely culprit in https://github.com/skarnet/tipidee/blame/fe95ed0a9f701f6ca076b403c0b2bf6cf15a8174/src/tipideed/cgi.c#L284. Removing the `if` and making it explicitly state `Content-Length: 0` seems to make the CGI redirect work, though I'm not sure if it will break something else.

___

Another kind of related issue is the presence of the `local_redirect` function; if a CGI script gets a POST request and returns 303, the request type will stay POST and pressing F5 will cause the data to be resubmitted.

**Comment by skarnet** [comment]
About Content-Length: A Content-Length of 0 should already be submitted on redirections in the git head. Is there a case where it's not?

About local redirects: what would be the semantics of a 303 status code with a local redirection? complete the URI with the current host? It seems I have some more work to do with 30x responses.

**Comment by capezotte** [comment]
> About Content-Length: A Content-Length of 0 should already be submitted on redirections in the git head. Is there a case where it's not?

When the redirection comes from a CGI script (or whenever the CGI response has just headers and an empty body).

> About local redirects: what would be the semantics of a 303 status code with a local redirection? complete the URI with the current host? It seems I have some more work to do with 30x responses.

303 means the user agent should make a second request, this time a GET (cursory reading of the HTTP spec seems to suggest you can leave an absolute path in the Location response and the browser will figure it out).

I think making local redirects only happen if explicit Status is not given by the script will work (after all, CGI local redirects MUST™ not contain any other headers, according to the spec).

**Comment by skarnet** [comment]
Fixed the Content-Length thing in the latest git; indeed the header should be written even when it's 0.

For local redirections, however, I don't understand. Local redirections only happen when the CGI returns a Location that is *not* a full URI, in which case the client doesn't even know because the server immediately serves a different resource. The Status code doesn't even matter when a redirection is processed locally (except that it must be 3xx, of course). Am I missing something?

**Comment by capezotte** [comment]
I'm arguing that CGI scripts that output a Location as a well as a Status header should work like a client redirect rather than a local redirect so the HTTP semantics intended by the CGI script author are conserved.

I gave one such example -- scripts that handle a POST request then return an HTTP 303 can't redirect the client to the bookmarkable URL and reloading the page triggers a second POST instead of a GET.

I do understand client redirects without document, especially with relative URIs, are undefined behavior in the CGI spec, though.

**Comment by skarnet** [comment]
But that's just not what the [CGI specification](https://datatracker.ietf.org/doc/html/rfc3875#section-6.2.2) says! When the Location header is local, the server has to process it locally, without involving the client. It would be much simpler code-wise to send everything to the client no matter what, and that's what I would have done, but we have no choice here.

**Comment by capezotte** [comment]
Since the CGI spec says local redirections "must not contain any other headers", I'd say scripts giving out a Status themselves don't follow the CGI spec and the server should either reject them or treat them as client redirections without document as an extension.

Either way, HTML redirections are close enough. I'm going to patch the script to return those instead.

**Comment by skarnet** [comment]
The CGI specification really isn't clear on what rule preempts what other rule. Especially with redirection, finding an order of operations that was non-contradictory with every part of the spec was a headache; I'm not surprised that the interpretation I found is non-unique and your interpretation is conformant as well.
